#!/bin/bash

rm *.tar.gz
rm -rf tmp_vnfd

build_vnfd () {
# Generate compiled charm
#pushd $1/charms/ansible-charm
#rm -rf builds/ deps/
#charm build
#popd

# Copy compiled charm to vnfd/charms
#cp -R $1/charms/ansible-charm/builds/ansible-charm $1/vnfd/charms/

# generate tar.gz
mkdir tmp_$1
cp -r $1/vnfd/* tmp_$1
cd tmp_$1
find * -type f -print | while read line; do md5sum $line >> checksums.txt; done
cd ..
tar -czvf $1_vnf.tar.gz tmp_$1
rm -rf tmp_$1
}

echo "----- Build the Server NFD -------"
build_vnfd testing_hydra_server

#echo "----- Build the VBS NFD -------"
#build_vnfd marathon_vbs

#echo "----- Build the VUE1 NFD -------"
#build_vnfd marathon_vue1
#
#echo "----- Build the VUE2 NFD -------"
#build_vnfd marathon_vue2
#
#echo "----- Build the VUE3 NFD -------"
#build_vnfd marathon_vue3

echo "----- Building the BASIC NS -------"
mkdir tmp_ns
cp -r testing_ns/* tmp_ns
cd tmp_ns
find * -type f -print | while read line; do md5sum $line >> checksums.txt; done
cd ..
tar -czvf testing_ns.tar.gz tmp_ns
rm -rf tmp_ns
